# Setup

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"


from crispr_millipede import encoding as cme
from crispr_millipede import modelling as cmm

In [3]:
import pandas as pd
import numpy as np

from Bio import SeqIO
from Bio.Seq import Seq

import matplotlib.pyplot as plt

In [5]:
amplicon = "ACATGCTCTAGTGAAAGCCAGTCTGGGCAGCTGGGTAGCTAATGAGGGGATTAGAGAGATTTTGTTGAATGAAAGGCAGATTGAGTCCTGCTACTCGCCCCCTTCATTCCCCTTCATTCATGCCTCATTCTTCCGCCTCCCAGCCGCCTCAACTGGCCAAAGGGAAGTGGAGGCCCTGCCACCTGTAGGGAGGGTCCCCTGGGGCTTGCCCACAGCAAACAGGAAGTCACAGCCTGGTGAGATGGGCCTGGGAATCAGCCACTGAGAAAGTGGGTCTCTTGGGTCCCTGAATTCTTTTTCTGAGTCCCTGCAGCAGTGAAAAAGACACAGAGGCACATAGAGAGTG"
print(f"Length of amplicon {len(amplicon)}")

Length of amplicon 346

# Production

## Encoding

In [6]:
design_matrix_spec = cmm.MillipedeDesignMatrixProcessingSpecification(
    wt_normalization=False,
    total_normalization=True,
    sigma_scale_normalized=True,
    decay_sigma_scale=True,
    K_enriched=5,
    K_baseline=5,
    a_parameter=0.0005,
    set_offset_as_presort = True,
    offset_normalized = False,
    offset_psuedocount = 1 # OTHERWISE will get infinity error when taking log(count +1) for offset, since 0 counts could be acceptable depending on thresholding
)

millipede_model_specification_set = {
    "joint_replicate_per_experiment_models" : cmm.MillipedeModelSpecification(
        model_types=[cmm.MillipedeModelType.NORMAL_SIGMA_SCALED, cmm.MillipedeModelType.NORMAL],
        replicate_merge_strategy=cmm.MillipedeReplicateMergeStrategy.COVARIATE,
        experiment_merge_strategy=cmm.MillipedeExperimentMergeStrategy.SEPARATE,
        S = 5,
        tau = 0.01,
        tau_intercept = 0.0001,
        cutoff_specification=cmm.MillipedeCutoffSpecification(
            per_replicate_each_condition_num_cutoff = 0, 
            per_replicate_all_condition_num_cutoff = 1, 
            all_replicate_num_cutoff = 0, 
            all_experiment_num_cutoff = 0,
            baseline_pop_all_condition_each_replicate_num_cutoff = 3,
            baseline_pop_all_condition_acceptable_rep_count = 2,
            enriched_pop_all_condition_each_replicate_num_cutoff = 3,
            enriched_pop_all_condition_acceptable_rep_count = 2,
            presort_pop_all_condition_each_replicate_num_cutoff = 3,
            presort_pop_all_condition_acceptable_rep_count = 2,
            
        ),
        design_matrix_processing_specification=design_matrix_spec
    )
}

In [7]:
paired_end_experiments_inputdata_denoised = cmm.MillipedeInputDataExperimentalGroup(
    data_directory="./", 
    enriched_pop_fn_experiment_list = ["20240807_v0_1_84_encoding_dataframes_denoised_removed_ABE8e_encodings_rep{}.tsv"],
    enriched_pop_df_reads_colname = "#Reads_CD19minus",
    baseline_pop_fn_experiment_list = ["20240807_v0_1_84_encoding_dataframes_denoised_removed_ABE8e_encodings_rep{}.tsv"],
    baseline_pop_df_reads_colname = "#Reads_CD19plus", 
    presort_pop_fn_experiment_list = ["20240807_v0_1_84_encoding_dataframes_denoised_removed_ABE8e_encodings_rep{}.tsv"],
    presort_pop_df_reads_colname = '#Reads_presort',
    experiment_labels = ["ABE8e"],
    reps = [0,1,2],
    millipede_model_specification_set = millipede_model_specification_set
   )

Performing initial input validation checks...
Passed validation.
Retrieving data for
	Replicate Merge Strategy: MillipedeReplicateMergeStrategy.COVARIATE
	Experiment Merge Strategy MillipedeExperimentMergeStrategy.SEPARATE
	Cutoff:
                    per_replicate_each_condition_num_cutoff=0,
                    per_replicate_presort_condition_num_cutoff=0,
                    per_replicate_all_condition_num_cutoff=1,
                    all_replicate_num_cutoff=0,
                    all_experiment_num_cutoff=0,
                    baseline_pop_per_condition_acceptable_rep_count=0,
                    baseline_pop_per_condition_acceptable_rep_count=0,
                    baseline_pop_per_condition_acceptable_rep_count=0,
                    enriched_pop_per_condition_each_replicate_num_cutoff=0,
                    enriched_pop_per_condition_acceptable_rep_count=0,
                    presort_pop_per_condition_each_replicate_num_cutoff=0,
                    presort_pop_per_condition_acceptable_rep_count=0,
                    baseline_pop_all_condition_each_replicate_num_cutoff=3,
                    baseline_pop_all_condition_acceptable_rep_count=2,
                    enriched_pop_all_condition_each_replicate_num_cutoff=3,
                    enriched_pop_all_condition_acceptable_rep_count=2,
                    presort_pop_all_condition_each_replicate_num_cutoff=3,
                    presort_pop_all_condition_acceptable_rep_count=2
	MatrixProcessing: wt_normalization=False;total_normalization=True;sigma_scale_normalized=True;decay_sigma_scale=True;K_enriched=5;K_baseline=5;a_parameter=0.0005; set_offset_as_default=False, set_offset_as_total_reads=False, set_offset_as_enriched=False, set_offset_as_baseline=False, set_offset_as_presort=True, offset_normalized=False, offset_psuedocount=1
Running all-condition filtering with enriched_num_cutoff=3, enriched_acceptable_rep_count=2, baseline_num_cutoff=3, baseline_acceptable_rep_count=2, presort_num_cutoff=3, presort_acceptable_rep_count=2

## Count Table

In [8]:
data = paired_end_experiments_inputdata_denoised.millipede_model_specification_set_with_data['joint_replicate_per_experiment_models'][1].data[0]
alleles = [data[data['intercept_exp0_rep0'] == 1], data[data['intercept_exp0_rep1'] == 1], data[data['intercept_exp0_rep2'] == 1]]

In [9]:
allele_tables = []

for rep in range(3):
    cols = list(alleles[rep].columns.values)
    restricted_cols = [col for col in cols if ">" in col]
    
    label = []
    edits = []
    
    minus = []
    plus = []
    presort = []    

    for index, row in alleles[rep].iterrows():
        row_restricted = row[restricted_cols]
        cols_selected = row_restricted[row_restricted == 1].index.tolist()
        
        allele = amplicon
        for col in cols_selected:
            demarker = col.find(">")
            pos = int(col[:demarker - 1])
            alt = col[demarker+1:]
            allele = allele[:pos] + alt + allele[pos + 1:]
                 
        if len(cols_selected) == 0:
            edits.append("wt")
        else:
            edits.append(",".join(cols_selected))
        
        minus.append(row["#Reads_CD19minus_raw"])
        plus.append(row["#Reads_CD19plus_raw"])
        
    dicto = {"edits": edits,
             "CD19minus_rep" + str(rep + 1): minus,
             "CD19plus_rep" + str(rep + 1): plus}
    
    allele_tables.append(pd.DataFrame(dicto).set_index("edits"))

In [10]:
#Drop columns with insufficient read count

'''
for table in allele_tables:
    for index, row in table.iterrows():
        total_count = row["CD19minus"] + row["CD19plus"] + row["presort"]
        if total_count < 10:
            table.drop(index, inplace = True)
'''

'\nfor table in allele_tables:\n    for index, row in table.iterrows():\n        total_count = row["CD19minus"] + row["CD19plus"] + row["presort"]\n        if total_count < 10:\n            table.drop(index, inplace = True)\n'

In [11]:
merged_df = pd.merge(allele_tables[0], allele_tables[1], on='edits', how='outer').fillna(0)
merged_df = pd.merge(merged_df, allele_tables[2], on='edits', how='outer').fillna(0)

In [12]:
count_df = merged_df.T
count_df.index.names = ['sample']

In [13]:
count_df

edits,wt,324A>G,322A>G,"322A>G,324A>G",321A>G,"321A>G,324A>G","321A>G,322A>G","321A>G,322A>G,324A>G",320A>G,"320A>G,322A>G,324A>G",...,"49A>G,52A>G,311A>G,314A>G","40A>G,41A>G,254T>C","36A>G,270T>C,274T>C,276T>C,278T>C,279T>C","36A>G,41A>G","36A>G,40A>G,112T>C,113T>C","35T>C,39T>C,274T>C,276T>C,278T>C,279T>C","35T>C,39T>C,42T>C,254T>C","35T>C,39T>C,42T>C,148T>C,153T>C","28A>G,36A>G,112T>C,113T>C","21T>C,314A>G,318A>G,319A>G,320A>G"
sample,,,,,,,,,,,,,,,,,,,,,
CD19minus_rep1,359314.0,856.0,413.0,208.0,146.0,4.0,3.0,186.0,84.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CD19plus_rep1,345867.0,463.0,401.0,267.0,144.0,3.0,1.0,41.0,51.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CD19minus_rep2,374063.0,677.0,397.0,441.0,165.0,25.0,11.0,145.0,57.0,0.0,...,1.0,3.0,6.0,53.0,1.0,3.0,21.0,3.0,3.0,22.0
CD19plus_rep2,416616.0,707.0,471.0,275.0,162.0,0.0,1.0,21.0,86.0,0.0,...,13.0,0.0,3.0,5.0,25.0,2.0,0.0,1.0,0.0,0.0
CD19minus_rep3,285837.0,505.0,342.0,173.0,107.0,48.0,4.0,117.0,101.0,0.0,...,0.0,4.0,0.0,7.0,0.0,3.0,7.0,1.0,3.0,6.0
CD19plus_rep3,371719.0,552.0,321.0,373.0,190.0,2.0,2.0,91.0,68.0,16.0,...,3.0,0.0,5.0,0.0,26.0,2.0,0.0,4.0,0.0,1.0

In [ ]:
count_df.to_csv('ABEPyDESEQ2CountTable.csv', sep="\t")

## Metadata Table

In [14]:
samples = list(count_df.index)
condition = ["CD19-", "CD19+"] * 3
replicate = [1, 1, 2, 2, 3, 3]
metadata_dict = {"sample": samples,
                 "condition": condition,
                 "replicate": replicate}

metadata_df = pd.DataFrame(metadata_dict).set_index("sample")

In [15]:
metadata_df

               condition  replicate
sample
CD19minus_rep1     CD19-          1
CD19plus_rep1      CD19+          1
CD19minus_rep2     CD19-          2
CD19plus_rep2      CD19+          2
CD19minus_rep3     CD19-          3
CD19plus_rep3      CD19+          3